table dim_date
	lineageTag: 919ac6eb-024a-5ade-a995-94816ee95ea0
	dataCategory: Time

	column date_key
		dataType: int64
		formatString: 0
		lineageTag: 338b44e3-20b6-5a7d-9cd4-006b5fd3e9ad
		summarizeBy: none
		sourceColumn: date_key

	column date
		dataType: dateTime
		formatString: yyyy-mm-dd
		isKey
		lineageTag: dc5b7be6-7323-5798-ba90-880d83083a64
		summarizeBy: none
		sourceColumn: date

	column year
		dataType: int64
		formatString: 0
		lineageTag: e99a3a6f-50b5-59be-baa1-255d8d9a7e6c
		summarizeBy: none
		sourceColumn: year

	column quarter
		dataType: string
		lineageTag: 8e53071b-130e-59e2-9ad0-51f405c62cfb
		summarizeBy: none
		sourceColumn: quarter

	column month_num
		dataType: int64
		formatString: 0
		lineageTag: c64699bb-905b-5e94-9f7b-f3142db21a78
		summarizeBy: none
		sourceColumn: month_num

	column month_name
		dataType: string
		lineageTag: 372d2168-bcc5-590a-ad99-fa3e68b253dd
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: month_num

	column year_month
		dataType: string
		lineageTag: 0e3983c7-4bfd-55e5-97db-8fe4f4e09d36
		summarizeBy: none
		sourceColumn: year_month

	column day_of_week
		dataType: string
		lineageTag: aaff7aa3-de34-51a2-ae6f-f4e26c5f83a7
		summarizeBy: none
		sourceColumn: day_of_week

	column is_weekend
		dataType: int64
		formatString: 0
		lineageTag: 13c8889c-56dc-5e0c-93e4-947000778bcb
		summarizeBy: none
		sourceColumn: is_weekend

	column fiscal_year_in
		dataType: string
		lineageTag: f82d33ca-e93c-5f2e-8381-6c3f776a6f85
		summarizeBy: none
		sourceColumn: fiscal_year_in

	column is_rbi_fx_day
		dataType: int64
		formatString: 0
		lineageTag: 4916d6d9-c190-57e5-b7aa-8f2aba4a29ba
		summarizeBy: none
		sourceColumn: is_rbi_fx_day

	column is_us_h10_day
		dataType: int64
		formatString: 0
		lineageTag: dd8fdad6-9d80-52a4-9ab0-42abbb3bead2
		summarizeBy: none
		sourceColumn: is_us_h10_day

	column rbi_listed_holiday
		dataType: int64
		formatString: 0
		lineageTag: 542c7820-1c4d-5d88-8d83-e85a597f20bc
		summarizeBy: none
		sourceColumn: rbi_listed_holiday

	partition dim_date = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\dim_date.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Nulls = Table.TransformColumns(Promoted, List.Transform(Table.ColumnNames(Promoted), (c) => {c, each if _ = "" then null else _})),
				    Typed = Table.TransformColumnTypes(Nulls, {{"date_key", Int64.Type}, {"date", type date}, {"year", Int64.Type}, {"quarter", type text}, {"month_num", Int64.Type}, {"month_name", type text}, {"year_month", type text}, {"day_of_week", type text}, {"is_weekend", Int64.Type}, {"fiscal_year_in", type text}, {"is_rbi_fx_day", Int64.Type}, {"is_us_h10_day", Int64.Type}, {"rbi_listed_holiday", Int64.Type}}, "en-US")
				in
				    Typed

